Add PRP, and PRF implies PRP
sarahscheffler/mapofcrypto pull request #23
Opened 2018-11-03 20:25 UTC by wyatt-howe

Also fixed minor JS bug when adding new nodes

2018-11-05 20:01 UTC, sarahscheffler requested changes
I added a brief description of the method that builds a PRP from a PRF and added the according citations.  Could you add them?

2018-11-05 20:01 UTC, sarahscheffler commented on objects/Edges/PRF_E_implies_E_PRP.json
> +    "page_number": "Section 1.1",
The actual method is in Section 5 (Page 380)

2018-11-05 20:01 UTC, sarahscheffler commented on objects/Edges/PRF_E_implies_E_PRP.json
> +    "long_description": "If pseudorandom functions exist, then pseudorandom permutations exist.  Starting with a PRF $G : \\{0,1\\}^n \\rightarrow \\{0,1\\}^{n}$.  We can construct a PRP $F : \\{0,1\
In addition, we should say the actual method:

Specifically, doing three rounds of a Feistel network (originally \cite{feistel1973cryptography}, explained more fully in \cite{schneier1996unbalanced}) with a PRF as the round function will yield a PRP.

2018-11-05 20:01 UTC, sarahscheffler commented on objects/Citations/Citations.bib
> +}
I added additional references
@article{feistel1973cryptography,
  title={Cryptography and computer privacy},
  author={Feistel, Horst},
  journal={Scientific american},
  volume={228},
  number={5},
  pages={15--23},
  year={1973},
  publisher={JSTOR},
  howpublished="\url{https://www.jstor.org/stable/24923044}"
}

@inproceedings{schneier1996unbalanced,
  title={Unbalanced Feistel networks and block cipher design},
  author={Schneier, Bruce and Kelsey, John},
  booktitle={International Workshop on Fast Software Encryption},
  pages={121--144},
  year={1996},
  organization={Springer},
  howpublished="\url{https://www.schneier.com/academic/paperfiles/paper-unbalanced-feistel.pdf}"
}

2018-11-05 20:01 UTC, sarahscheffler commented on objects/Edges/PRF_E_implies_E_PRP.json
> +    "submitter": "wyatt-howe",
Since I'm adding info, can you add me as a verifier?
`"verifier": "sarahscheffler",`

2018-11-06 18:45 UTC, sarahscheffler commented on objects/Citations/Citations.bib
> +  howpublished="\url{https://pdfs.semanticscholar.org/7d58/9564998287a942149c4fee931852b22d8997.pdf}"
This URL leads to a paper by Pieprzyk.

The paper you're referencing can be found at [https://epubs.siam.org/doi/abs/10.1137/0217022](https://epubs.siam.org/doi/abs/10.1137/0217022)

2018-11-15 04:22 UTC, wyatt-howe commented
Changes made – this update should be ready to merge now.  Thanks for correcting what I missed

2018-11-20 14:45 UTC, merged